models/Congresoinscripcion.php
<?php

namespace app\models;

use Yii;
use yii\swiftmailer\Mailer;
/**
 * This is the model class for table "congresoinscripcion".
 *
 * @property integer $id
 * @property integer $dni
 * @property string $nombre
 * @property integer $idmodalidad
 * @property string $telefono
 * @property string $email
 * @property string $pais
 * @property string $ciudad
 * @property string $nombreponencia
 * @property string $cargo
 * @property string $institucion
 * @property string $direccion
 * @property string $nombre1
 * @property integer $tipo1
 * @property string $nombre2
 * @property integer $tipo2
 * @property string $nombre3
 * @property integer $tipo3
 *
 * @property Congresomodalidad $tipo30
 * @property Congresoparticipacion $idmodalidad0
 * @property Congresomodalidad $tipo10
 * @property Congresomodalidad $tipo20
 */
class Congresoinscripcion extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'congresoinscripcion';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['dni', 'nombre', 'idmodalidad', 'telefono', 'email', 'pais', 'ciudad', 'direccion' ], 'required'],
            [['dni', 'idmodalidad', 'tipo1', 'tipo2', 'tipo3', 'acreditado','modalparticip'], 'integer'],
            [['nombre', 'pais', 'ciudad', 'cargo', 'institucion', 'direccion'], 'string', 'max' => 100],
            [['telefono'], 'string', 'max' => 30],
            [['email'], 'string', 'max' => 50],
            [['email'], 'email'],
            [['pagofecha', 'pagomonto'], 'string', 'max' => 15],
            [['nombreponencia', 'nombre1', 'nombre2', 'nombre3', 'observacion'], 'string', 'max' => 300]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'dni' => 'DNI o Pasaporte',
            'nombre' => 'Nombre Completo',
            'idmodalidad' => 'Categoría de participante',
            'telefono' => 'Teléfono',
            'email' => 'Email',
            'pais' => 'País',
            'ciudad' => 'Ciudad',            
            'cargo' => 'Cargo',
            'institucion' => 'Institución',
            'direccion' => 'Dirección',
            'nombre1' => 'Nombre de la Ponencia (I)',
            'tipo1' => 'Modalidad',
            'nombre2' => 'Nombre de la Ponencia (II)',
            'tipo2' => 'Modalidad',
            'nombre3' => 'Nombre de la Ponencia (III)',
            'tipo3' => 'Modalidad',
            'modalparticip' => 'Modalidad de Participación',
            'pagofecha' => 'Fecha en que pago', 
            'pagomonto' => 'Monto abonado', 
            'observacion' => 'Observación', 
            'acreditado' => 'Acreditado'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipo30()
    {
        return $this->hasOne(Congresomodalidad::className(), ['id' => 'tipo3']);
    }
    
    public function getModalparticip0()
    {
               return $this->hasOne(Congresomodalparticip::className(), ['id' => 'modalparticip']);
   }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdmodalidad0()
    {
        return $this->hasOne(Congresoparticipacion::className(), ['id' => 'idmodalidad']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipo10()
    {
        return $this->hasOne(Congresomodalidad::className(), ['id' => 'tipo1']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipo20()
    {
        return $this->hasOne(Congresomodalidad::className(), ['id' => 'tipo2']);
    }
   
}

controllers/CongresoinscripcionController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Congresoinscripcion;
use app\models\CongresoinscripcionSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use mPDF;

/**
 * CongresoinscripcionController implements the CRUD actions for Congresoinscripcion model.
 */
class CongresoinscripcionController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Congresoinscripcion models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CongresoinscripcionSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }
  public function actionIndexadmin()
    {
        $searchModel = new CongresoinscripcionSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());

        return $this->render('indexadmin', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }
    
     public function actionIndexcertified()
    {
        $searchModel = new CongresoinscripcionSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());

        return $this->render('indexcertified', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }
    public function actionIndexexterno()
    {
        $searchModel = new CongresoinscripcionSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());

        return $this->render('indexexterno', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }
    /**
     * Displays a single Congresoinscripcion model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    
    public function actionViewprint($id)
    {        
        $model = $this->findModel($id);
        if ($model->acreditado ==1)
        {
            $mpdf = new mPDF('c', 'A4-L');
            $mpdf->WriteHTML($this->render('viewCertificado', [
                'model' => $model,
            ]));
            $mpdf->Output();
        }        
        else {
            return ($this->render('viewCertificadoError', [
                'model' => $model,
            ]));
        }
        
    }
    /**
     * Creates a new Congresoinscripcion model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Congresoinscripcion;
 
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
           Yii::$app->mail->compose('html',['$model'=>$model])
                ->setFrom('secretaria.investigacion@fatu.uncoma.edu.ar')
                ->setTo($model->email)
                ->setSubject('VI Congreso Latinoamericano de Investigación Turística')
                ->setHtmlBody($this->render('view', [
            'model' => $model,
        ]))
                ->send();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
public function actionMail()
    {
// Yii::$app->mail->compose('html',[])
//    ->setFrom('secretaria.investigacion@fatu.uncoma.edu.ar')
//    ->setTo('fede.amigone@gmail.com')
//    ->setSubject('esto es una mierda')
//    ->send();
    
Yii::$app->mail->compose('html',[])
                ->setFrom('secretaria.investigacion@fatu.uncoma.edu.ar')
                ->setTo('fede.amigone@gmail.com')
                ->setSubject('VI Congreso Latinoamericano de Investigación Turística')
                ->send();    
        
    }
     
 
 
    
    /**
     * Updates an existing Congresoinscripcion model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['indexadmin']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Congresoinscripcion model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['indexadmin']);
    }

    /**
     * Finds the Congresoinscripcion model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Congresoinscripcion the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Congresoinscripcion::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/congresoinscripcion/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
/**
 * @var yii\web\View $this
 * @var app\models\Congresoinscripcion $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="congresoinscripcion-form">

    <?php $form = ActiveForm::begin(); ?>
    
    <?= $form->field($model, 'dni')->textInput() ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => 100]) ?>
    
    
    <?= $form->field($model, 'modalparticip')->dropDownList(ArrayHelper::map(\app\models\Congresomodalparticip::find()->all(),'id','nombre'))?>           
    
    <?= $form->field($model, 'idmodalidad')->dropDownList(ArrayHelper::map(\app\models\Congresoparticipacion::find()->all(),'id','nombre'))?>           

    <?= $form->field($model, 'telefono')->textInput(['maxlength' => 30]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => 50]) ?>

    <?= $form->field($model, 'pais')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'ciudad')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'direccion')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'nombre1')->textInput(['maxlength' => 300]) ?>

    <?= $form->field($model, 'tipo1')->dropDownList(ArrayHelper::map(\app\models\Congresomodalidad::find()->all(),'id','nombre'), ['prompt' => '--Seleccionar si es Expositor--'])?>           

    <?= $form->field($model, 'nombre2')->textInput(['maxlength' => 300]) ?>

    <?= $form->field($model, 'tipo2')->dropDownList(ArrayHelper::map(\app\models\Congresomodalidad::find()->all(),'id','nombre'), ['prompt' => '--Seleccionar si es Expositor--'])?>           

    <?= $form->field($model, 'nombre3')->textInput(['maxlength' => 300]) ?>

    <?= $form->field($model, 'tipo3')->dropDownList(ArrayHelper::map(\app\models\Congresomodalidad::find()->all(),'id','nombre'), ['prompt' => '--Seleccionar si es Expositor--'])?>           

    <?= $form->field($model, 'cargo')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'institucion')->textInput(['maxlength' => 100]) ?>

    

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Guardar' : 'Modificar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/congresoinscripcion/_formadmin.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
/**
 * @var yii\web\View $this
 * @var app\models\Congresoinscripcion $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="congresoinscripcion-form">

    <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($model, 'dni')->textInput() ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => 100]) ?>
    
    
    <?= $form->field($model, 'modalparticip')->dropDownList(ArrayHelper::map(\app\models\Congresomodalparticip::find()->all(),'id','nombre'))?>           
    
    <?= $form->field($model, 'idmodalidad')->dropDownList(ArrayHelper::map(\app\models\Congresoparticipacion::find()->all(),'id','nombre'))?>           

    <?= $form->field($model, 'telefono')->textInput(['maxlength' => 30]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => 50]) ?>

    <?= $form->field($model, 'pais')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'ciudad')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'direccion')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'nombre1')->textInput(['maxlength' => 300]) ?>

    <?= $form->field($model, 'tipo1')->dropDownList(ArrayHelper::map(\app\models\Congresomodalidad::find()->all(),'id','nombre'), ['prompt' => '--Seleccionar si es Expositor--'])?>           

    <?= $form->field($model, 'nombre2')->textInput(['maxlength' => 300]) ?>

    <?= $form->field($model, 'tipo2')->dropDownList(ArrayHelper::map(\app\models\Congresomodalidad::find()->all(),'id','nombre'), ['prompt' => '--Seleccionar si es Expositor--'])?>           

    <?= $form->field($model, 'nombre3')->textInput(['maxlength' => 300]) ?>

    <?= $form->field($model, 'tipo3')->dropDownList(ArrayHelper::map(\app\models\Congresomodalidad::find()->all(),'id','nombre'), ['prompt' => '--Seleccionar si es Expositor--'])?>           

    <?= $form->field($model, 'cargo')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'institucion')->textInput(['maxlength' => 100]) ?>
    
    <?= $form->field($model, 'pagofecha')->textInput(['maxlength' => 15]) ?> 
 
    <?= $form->field($model, 'pagomonto')->textInput(['maxlength' => 15]) ?> 
 
    <?= $form->field($model, 'observacion')->textInput(['maxlength' => 300]) ?> 
    
    <?= $form->field($model, 'acreditado')->checkbox([1 =>'Acreditado']) ?> 

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Guardar' : 'Modificar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/congresoinscripcion/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\CongresoinscripcionSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="congresoinscripcion-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'dni') ?>

    <?= $form->field($model, 'nombre') ?>

    <?= $form->field($model, 'idmodalidad') ?>

    <?= $form->field($model, 'telefono') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'pais') ?>

    <?php // echo $form->field($model, 'ciudad') ?>

    <?php // echo $form->field($model, 'nombreponencia') ?>

    <?php // echo $form->field($model, 'cargo') ?>

    <?php // echo $form->field($model, 'institucion') ?>

    <?php // echo $form->field($model, 'direccion') ?>

    <?php // echo $form->field($model, 'nombre1') ?>

    <?php // echo $form->field($model, 'tipo1') ?>

    <?php // echo $form->field($model, 'nombre2') ?>

    <?php // echo $form->field($model, 'tipo2') ?>

    <?php // echo $form->field($model, 'nombre3') ?>

    <?php // echo $form->field($model, 'tipo3') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/congresoinscripcion/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Congresoinscripcion $model
 */

$this->title = 'Por favor, ingrese sus datos.';
//$this->params['breadcrumbs'][] = ['label' => 'Congresoinscripcions', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="congresoinscripcion-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/congresoinscripcion/createadmin.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Congresoinscripcion $model
 */

$this->title = 'Por favor, ingrese sus datos.';
//$this->params['breadcrumbs'][] = ['label' => 'Congresoinscripcions', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="congresoinscripcion-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formadmin', [
        'model' => $model,
    ]) ?>

</div>

views/congresoinscripcion/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\CongresoinscripcionSearch $searchModel
 */

$this->title = 'Inscriptos';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="congresoinscripcion-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
      
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'nombre',
            'dni',
            
            'idmodalidad0.nombre',
            'telefono',
             'email:email',
             'pais',
             'ciudad',             
             'cargo',
             'institucion',
             'direccion',
             'nombre1',
             'tipo10.nombre',
             'nombre2',
             'tipo20.nombre',
             'nombre3',
             'tipo30.nombre',
            'modalparticip',
            
    

             ['class' => 'yii\grid\ActionColumn',
            'template'=>'{view}',
                ]
        ],
    ]); ?>

</div>

views/congresoinscripcion/indexadmin.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\CongresoinscripcionSearch $searchModel
 */

$this->title = 'Inscriptos';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="congresoinscripcion-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php // echo $this->render('_search', ['model' => $searchModel]); 
    
    ?>

    <p>
      
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'nombre',
            'dni',                        
            'pagofecha',
            'pagomonto',
            'observacion',
            'acreditado',
               ['class' => 'yii\grid\ActionColumn',
                   
            ],
        ],
    ]); ?>

</div>

views/congresoinscripcion/indexcertified.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\CongresoinscripcionSearch $searchModel
 */

$this->title = 'Inscriptos';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="congresoinscripcion-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php // echo $this->render('_search', ['model' => $searchModel]); 
    
    ?>

    <p>
      
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,    
        'columns' => [     
            ['class' => 'yii\grid\SerialColumn'],
            'nombre',
            'dni',                        
            ['class' => 'yii\grid\ActionColumn',
               'template' => '{Imprimir}',
                'buttons' => [
                'Imprimir' => function ($url, $model) {
                return Html::a('Imprimir', ['/congresoinscripcion/viewprint', 'id' => $model->id]);
                     },
                ],
            ],
        ],
    ]); ?>

</div>

views/congresoinscripcion/indexexterno.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\CongresoinscripcionSearch $searchModel
 */

$this->title = 'Inscriptos';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="congresoinscripcion-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
      
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'nombre',
            'dni',
            
            'idmodalidad0.nombre',
            'telefono',
             'email:email',
             'pais',
             'ciudad',             

    

             ['class' => 'yii\grid\ActionColumn',
            'template'=>'{view}',
                ]
        ],
    ]); ?>

</div>

views/congresoinscripcion/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Congresoinscripcion $model
 */

$this->title = 'Informar Pago: ' . $model->nombre;

?>
<div class="congresoinscripcion-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formadmin', [
        'model' => $model,
    ]) ?>

</div>

views/congresoinscripcion/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/**
 * @var yii\web\View $this
 * @var app\models\Congresoinscripcion $model
 */

$this->title = $model->nombre;
//$this->params['breadcrumbs'][] = ['label' => 'Congresoinscripcions', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="congresoinscripcion-view">
    <center>
    <hr>
            <h1>VI Congreso Latinoamericano de Investigación Turística</h1>
            <h2>Número de inscripción: <?=$model->id?> </h2>
            
            <?=Html::img('http://www.fatu-uncoma.com.ar/congreso/images/congreso_condet_2014.jpg',['height'=>'200px'])?>
<h1>Hemos registrado sus datos.</h1>
    <h3>Su inscripción fué enviada al correo suministrado.</h3>
    <hr>
    
    </center>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [       
            'dni',
            'nombre',
            'modalparticip0.nombre',
            'idmodalidad0.nombre',
            'telefono',
            'email:email',
            'pais',
            'ciudad',           
            'cargo',
            'institucion',
            'direccion',
            'nombre1',
            'tipo10.nombre',
            'nombre2',
            'tipo20.nombre',
            'nombre3',
            'tipo30.nombre',

      
        ],
    ]) ?>

</div>

views/congresoinscripcion/viewCertificado.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/**
 * @var yii\web\View $this
 * @var app\models\Congresoinscripcion $model
 */

$this->title = $model->nombre;

?>
<div class="congresoinscripcion-view">
<?=Html::img('img/certificado-superior.jpg')?>                    
    <center> 
        <u><h2>
            <p class="text-center">  <?=$model->nombre ?> </p>
        </h2></u>
    </center>
    <h4>
        <p class="text-center"> Participó en calidad de <?=$model->modalparticip0->nombre ?> en el "VI Congreso Latinoamericano de Investigación Turística" que se llevo a cabo en la ciudad de Neuquén los días 25,26 y 27 de septiembre del 2014. </p>
    </h4>    
    <p>        
        <Br>
    </p>
<?=Html::img('img/certificado-inferior.jpg')?>
</div>    

views/congresoinscripcion/viewCertificadoError.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/**
 * @var yii\web\View $this
 * @var app\models\Congresoinscripcion $model
 */

$this->title = $model->nombre;
//$this->params['breadcrumbs'][] = ['label' => 'Congresoinscripcions', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="congresoinscripcion-view">
    <center>
    <hr>
            <h1>Usted no se encuentra acreditado en nuestros registros</h1>
            <h2>Si esto es un error, por favor contactese al email: secretaria.extension@fatu.uncoma.edu.ar</h2>
            
            <?=Html::img('http://www.fatu-uncoma.com.ar/congreso/images/congreso_condet_2014.jpg',['height'=>'200px'])?>
    
    </center>

</div>