models/Congreponencia.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "congre_ponencia".
 *
 * @property integer $documento_id
 * @property string $documento_nombre
 * @property string $documento_archivo
 * @property string $documento_fechayhora
 * @property integer $documento_privilegios
 * @property string $documento_descripcion
 * @property integer $documento_activo
 */
class Congreponencia extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'congresoponencia';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['documento_nombre', 'documento_archivo', 'idtema' ], 'required'],
            [['documento_fechayhora'], 'safe'],            
            [['documento_privilegios', 'documento_activo' , 'idtema'], 'integer'],
            [['documento_nombre'], 'string', 'max' => 255],
            [['documento_archivo'], 'string'],
            [['documento_descripcion'], 'string', 'max' => 500]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'documento_id' => 'Documento ID',
            'documento_nombre' => 'Nombre de la Ponencia',
            'documento_archivo' => 'Archivo Ms Power Point',
            'documento_fechayhora' => 'Fecha y Hora',
            'documento_privilegios' => 'Privilegios',
            'documento_descripcion' => 'Descripción',
            'documento_activo' => 'Documento Activo',
            'idtema' => 'Categoría',
        ];
    }
    
     public function getIdtema0()
    {
        return $this->hasOne(Congresotemas::className(), ['id' => 'idtema']);
    }
}

controllers/CongreponenciaController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Congreponencia;
use app\models\CongreponenciaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;






/**
 * CongreponenciaController implements the CRUD actions for Congreponencia model.
 */
class CongreponenciaController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Congreponencia models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CongreponenciaSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Congreponencia model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Congreponencia model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
  

    
      public function actionDescargar($cambio_archivo)
    {

                $path = Yii::$app->basePath.DIRECTORY_SEPARATOR.'ponencias';   
                //Especificamos la ruta en donde se encuentran los archivos 
                //Yii:: Es una colección de funciones auxiliares útiles para Yii Framework
                //$app->basePath Nos da el directorio raiz de la aplicacion
                $file = $path.$cambio_archivo;
                //Concatena la ruta con el archivo a descargar($cambio_archivo)
                
                header('Content-disposition: attachment; filename='.$file);
                //Content-disposition proporciona un nombre de fichero recomendado y fuerza al navegador el mostarar el diálogo para guardar el fichero
                header("Content-Type: application/force-download");                
                
                $dirInfo = pathinfo($file); 
                //pathinfo Devuelve información acerca de la ruta de un fichero como un array asociativo, o bien como un string
                $nombre = $dirInfo['basename'];                                            
                $ext = $dirInfo['extension']; 
                //Asigna la extension del archivo a una variable
                                
                if(strtolower($ext) == 'ppt') //Pasa la extension a minuscula y la compara si es igual a pdf
                    header('application/vnd.ms-powerpoint'); //Si es igual a pdf abre la aplicacion para mostrar el pdf en la pagina                                                
                            
                header("Content-disposition: attachment; filename=".$nombre);
                //Content-disposition proporciona un nombre de fichero recomendado y fuerza al navegador el mostarar el diálogo para guardar el fichero 
                
                $file = file_get_contents($file);
                //file_get_contents() es la manera preferida de transmitir el contenido de un fichero a una cadena. Usa técnicas de mapeado de memoria, para mejorar el rendimiento
                
                echo $file;
                die;         //Muere la funcion(Termina)         

            }
    
     public function actionCreate()
    {
        $model = new Congreponencia;
        //Crea una nueva instancia de la clase EdmDocumento
        $band = false;
        //Crea una bandera con valor falso

        //if(isset($_POST['EdmDocumento'])){ //Entra al if si hay alguna variable enviada por post con el nombre 'EdmDocumento'
        if(isset($_POST['Congreponencia'])){ //Entra al if si hay alguna variable enviada por post con el nombre 'EdmDocumento'
    
            $model->load(Yii::$app->request->post());
            //A la instancia creada $model se le asigna todos los datos que vienen por post del formulario
            
            $file = UploadedFile::getInstance($model,'documento_archivo');
            //UploadedFile es una clase que representa la informacion de un archivo subido
            //A $file le asignamos la informacion del archivo subido
            
            if(is_object($file)){ //Comprueba si la variable $file es un objeto                   
                
                $extenssion = substr($file->name, -4); //Selecciona los ultimos 4 caracteres para obtener la extension y la asigna a la variable
                $nombreCifrado = $model->documento_nombre.microtime(); //Cifra en md5 la variable entregada por la funcion microtime y la asigna a la variable
                $nombreCifrado .= $extenssion ; //Adiciona a la variable anterior la extension del archivo
                $file->name = $nombreCifrado;//md5($file->name).$extenssion;
                $carpetatema = $model->idtema0->nombre;
                $path = Yii::$app->basePath.DIRECTORY_SEPARATOR.'ponencias'.DIRECTORY_SEPARATOR.$carpetatema;
                //Especificamos la ruta en donde se encuentran los archivos 
                //Yii:: Es una colección de funciones auxiliares útiles para Yii Framework
                //$app->basePath Nos da el directorio raiz de la aplicacion
                
                if(!is_dir($path)) //is_dir indica si el nombre de la ruta es un directorio, si es falso entra en el if 
                mkdir($path); //Crea un directorio con la ruta dada si no existe
                                     
                /* --------------------------------- */                                      
                $url   = $path.DIRECTORY_SEPARATOR.$file->name; //url definitiva al archivo (Donde guarda el archivo)                                                            
                $array = pathinfo($url); //Devuelve la informacion del URL como un array asociativo y la asigna a la variable
                $ext   = $array['extension']; //Asigna la extension a una variable
                $ext   = strtolower($ext); //Pasa a minuscula la extension                     
                /* --------------------------------- */                                      
                 
                if(empty($ext) or (($ext != 'ppt') and ($ext != 'pps') and ($ext != 'pptx'))){ 
                    //Si la extension esta vacia o es diferente de alguna de las extensiones escritas entra por el if
                      throw new \yii\web\HttpException(204, " Solo puede subir archivos con extension (.ppt) o (.pps) o (.pptx)");
                      //Muestra un error por subir un archivo con extension no  valida
                }
                else{                         
                     $file->saveAs($url); //Si entra por el else guarda el archivo en la ruta especificada
                     $band = true; //Cambia la bandera con el valor true
                }     
                                      
                /* --------------------------------------- */
                $model->documento_archivo    = $file->name; //Al modelo con el tag documento_archivo se le asigna el nombre del archivo

                //echo($model->documento_archivo); exit;                 
                //$model->documento_usuario    = Yii::$app->user->getState('idUsuario');
                
                //$model->documento_usuario    = Yii::$app->user->getId(); //Al modelo con el tag documento_usuario se le asigna el id del usuario
                $model->documento_activo     = 1;  //Al modelo con el tag documento_activo se le asigna 1 y siempre se pone como activo
                $model->documento_fechayhora = date('Y-m-d H:i:s'); //Asignamos a documento_fechayhora el el tiempo y fecha con la funcion date
                //$model->documento_proyecto = $idProyecto; //Al modelo con el tag documento_proyecto se le asigna el id del proyecto que entra por post
                
                //especifica los privilegios al crear los archivos;                
                //if (Yii::$app->user->can('cliente')) { //Si el usuario es cliente entra al if
                //    $model->documento_privilegios = 1; //Le asigna a documento_privilegios el valor 1(Publico)

                //}
                //else {
                //    $model->documento_privilegios = 2; //Le asigna a documento_privilegios el valor 2(Privado)
                //};                                        
            };                  
        }
                    if ($band && $model->save()){ //Si $band es true y pudo guardar los datos del modelo entra por el if
                        return $this->redirect(['view', 'id' => $model->documento_id]);} //Redirecciona a la vista del documento creado
                    else {
                        return $this->render('create', [ //Si entra por el else vuelve a renderizar la vista create
                            'model' => $model,
                        ]);
                    }                       
    }
    
    /**
     * Updates an existing Congreponencia model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->documento_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Congreponencia model.

views/congreponencia/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
/**
 * @var yii\web\View $this
 * @var app\models\Congreponencia $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="congreponencia-form">

    <?php $form = ActiveForm::begin([ 'options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'documento_nombre')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'documento_archivo')->fileInput() ?>

    <?= $form->field($model, 'documento_descripcion')->textInput(['maxlength' => 500]) ?>

    <?= $form->field($model, 'idtema')->dropDownList(ArrayHelper::map(\app\models\Congresotemas::find()->all(),'id','nombre'))?>           
    <div
        class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/congreponencia/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\CongreponenciaSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="congreponencia-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'documento_id') ?>

    <?= $form->field($model, 'documento_nombre') ?>

    <?= $form->field($model, 'documento_archivo') ?>

    <?= $form->field($model, 'documento_fechayhora') ?>

    <?= $form->field($model, 'documento_privilegios') ?>

    <?php // echo $form->field($model, 'documento_descripcion') ?>

    <?php // echo $form->field($model, 'documento_activo') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/congreponencia/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Congreponencia $model
 */

$this->title = 'Registrar Ponencia';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="congreponencia-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/congreponencia/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\CongreponenciaSearch $searchModel
 */

$this->title = 'Ponencias';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="congreponencia-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Congreponencia', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],


            'documento_nombre',
            'documento_archivo',
            'documento_fechayhora',
            'idtema0.nombre',

            // 'documento_descripcion',
            // 'documento_activo',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/congreponencia/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Congreponencia $model
 */

$this->title = 'Update Congreponencia: ' . $model->documento_id;
$this->params['breadcrumbs'][] = ['label' => 'Congreponencias', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->documento_id, 'url' => ['view', 'id' => $model->documento_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="congreponencia-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/congreponencia/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/**
 * @var yii\web\View $this
 * @var app\models\Congreponencia $model
 */

$this->title = $model->documento_nombre ;

?>
<div class="congreponencia-view">
    <h1>        
        Su Ponencia fué registrada exitosamente.
    </h1>   
    
   
    <p>
        <?php //echo Html::a('Descargar', ['congreponencia/descargar','cambio_archivo' => $model->documento_archivo], ['class' => 'btn btn-primary']);?>
    </p>


    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [            
            'documento_nombre',
            'documento_archivo',
            'documento_fechayhora',            
            'documento_descripcion',
            'idtema0.nombre',
            
        ],
    ]) ?>

</div>